# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('monto_solicitado', models.PositiveIntegerField()),
            ],
        ),
    ]
