# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_prestamo', '0002_auto_20171106_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=20),
        ),
    ]
