# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_prestamo', '0003_auto_20171107_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
